### ISSUE TITLE
Вот, другое дело

### ISSUE THREAD

**Issue by GigantPro** [KirillMerz/NSCMTelegramBotPython#1]
Здравствуйте! Я вам писал issue под другим таким же ботом, НО БЛЯТЬ НА GO. Так вот, это уже на много лучше)

**Comment by GigantPro** [comment]
Ну так что, отвечать будем епта?

**Comment by KirillMerz** [comment]
окстись, падаль швайтоновская

**Comment by GigantPro** [comment]
> окстись, падаль швайтоновская

Я считаю, что ты не прав по всем фронтам. САМ ТЫ ПАДАЛЬ, А Я ПАДАЛЬЩИК
